/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FoodService } from "./components/calories-tracker/add";
import { UnixTimestamp } from "./utils/unix-timestamp";
import { FoodService as FoodService1 } from "./components/calories-tracker/list";
import { FoodInformationService, FoodService as FoodService2 } from "./components/calories-tracker/scan-food";
export namespace Components {
    interface AddFood {
        "service": FoodService;
    }
    interface AppRoot {
    }
    interface BarcodeReader {
        "onCodeChange": (readCode: string) => void;
    }
    interface DateReader {
        "onDateChange": (date: UnixTimestamp) => void;
    }
    interface FoodList {
        "service": FoodService;
    }
    interface ScanFood {
        "foodInformationService": FoodInformationService;
        "foodService": FoodService;
    }
}
declare global {
    interface HTMLAddFoodElement extends Components.AddFood, HTMLStencilElement {
    }
    var HTMLAddFoodElement: {
        prototype: HTMLAddFoodElement;
        new (): HTMLAddFoodElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBarcodeReaderElement extends Components.BarcodeReader, HTMLStencilElement {
    }
    var HTMLBarcodeReaderElement: {
        prototype: HTMLBarcodeReaderElement;
        new (): HTMLBarcodeReaderElement;
    };
    interface HTMLDateReaderElement extends Components.DateReader, HTMLStencilElement {
    }
    var HTMLDateReaderElement: {
        prototype: HTMLDateReaderElement;
        new (): HTMLDateReaderElement;
    };
    interface HTMLFoodListElement extends Components.FoodList, HTMLStencilElement {
    }
    var HTMLFoodListElement: {
        prototype: HTMLFoodListElement;
        new (): HTMLFoodListElement;
    };
    interface HTMLScanFoodElement extends Components.ScanFood, HTMLStencilElement {
    }
    var HTMLScanFoodElement: {
        prototype: HTMLScanFoodElement;
        new (): HTMLScanFoodElement;
    };
    interface HTMLElementTagNameMap {
        "add-food": HTMLAddFoodElement;
        "app-root": HTMLAppRootElement;
        "barcode-reader": HTMLBarcodeReaderElement;
        "date-reader": HTMLDateReaderElement;
        "food-list": HTMLFoodListElement;
        "scan-food": HTMLScanFoodElement;
    }
}
declare namespace LocalJSX {
    interface AddFood {
        "service"?: FoodService;
    }
    interface AppRoot {
    }
    interface BarcodeReader {
        "onCodeChange"?: (readCode: string) => void;
    }
    interface DateReader {
        "onDateChange"?: (date: UnixTimestamp) => void;
    }
    interface FoodList {
        "service"?: FoodService;
    }
    interface ScanFood {
        "foodInformationService"?: FoodInformationService;
        "foodService"?: FoodService;
    }
    interface IntrinsicElements {
        "add-food": AddFood;
        "app-root": AppRoot;
        "barcode-reader": BarcodeReader;
        "date-reader": DateReader;
        "food-list": FoodList;
        "scan-food": ScanFood;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-food": LocalJSX.AddFood & JSXBase.HTMLAttributes<HTMLAddFoodElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "barcode-reader": LocalJSX.BarcodeReader & JSXBase.HTMLAttributes<HTMLBarcodeReaderElement>;
            "date-reader": LocalJSX.DateReader & JSXBase.HTMLAttributes<HTMLDateReaderElement>;
            "food-list": LocalJSX.FoodList & JSXBase.HTMLAttributes<HTMLFoodListElement>;
            "scan-food": LocalJSX.ScanFood & JSXBase.HTMLAttributes<HTMLScanFoodElement>;
        }
    }
}
